// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Portal_Project.Migrations
{
    [DbContext(typeof(RoundOneContext))]
    partial class RoundOneContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Portal_Project.Models.RoundOne", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("BSEdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("CE_MayContact")
                        .HasColumnType("bit");

                    b.Property<string>("CE_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CE_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CE_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CE_StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CurrentEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DesiredSalary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSCEdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HSCEdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LE_EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LE_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LE_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LE_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LE_StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MSEdu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneOne")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneSec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PositionAF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Qualification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SLE_EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SLE_Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLE_Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SLE_Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SLE_StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SecondLastEmp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Skills")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartEmpDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("canidateName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fatherName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RoundOne");
                });

            modelBuilder.Entity("Portal_Project.Models.Round_Three", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("ImageAdmin")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("ImageCand")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("RoundThree");
                });
#pragma warning restore 612, 618
        }
    }
}
